services:
  db:
    image: postgres:15
    container_name: ktzh_db
    restart: always
    environment:
      POSTGRES_DB: ktzh
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit_app:
    build: ../ktzh_python
    container_name: ktzh_back
    restart: always
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.baseUrlPath=back
    depends_on:
      - db

  nuxt_app:
    build:
      context: .
      dockerfile: Dockerfile.nuxt
    container_name: ktzh_front
    restart: always
    environment:
      - NUXT_APP_BASE_URL=/front/
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@db:5432/ktzh
    depends_on:
      - db

  gateway:
    image: nginx:alpine
    container_name: ktzh_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nuxt_app
      - streamlit_app

volumes:
  postgres_data:
